### ISSUE TITLE
Sig on a function that aliases a column causes a NoMethodError

### ISSUE THREAD

**Issue by lake-effect** [dduugg/yard-sorbet#227]
## Reduced example

Found a corner case that unfortunately affects a production codebase. Here's a reduced example:

```rb
class SomeThing < ApplicationRecord
  extend T::Sig

  validates :rate, presence: true

  sig { returns(T.nilable(Float)) }
  def rate
    result = super()
    if result
      result *= 5
    end
    result
  end
end

# == Schema Information
#
# Table name: some_things
#
#  id                     :integer          not null, primary key
#  rate                   :float
```

The idea behind this code is to massage the rate value on the table column with some other number (we use more complicated logic than `*= 5` in the actual code) before returning it.

## Error log

This throws when trying to generate YARD docs:
```
[error]: Unhandled exception in YARDSorbet::Handlers::SigHandler:
  in `app/models/health/family_rate.rb`:165:

	165: sig { returns(T.nilable(Float)) }

[error]: NoMethodError: undefined method `types' for {}:Hash
[error]: Stack trace:
	/Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/yard-0.9.28/lib/yard/docstring.rb:217:in `block in to_raw'
	/Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/yard-0.9.28/lib/yard/docstring.rb:208:in `map'
	/Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/yard-0.9.28/lib/yard/docstring.rb:208:in `to_raw'
	/Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/yard-sorbet-0.8.0/lib/yard-sorbet/handlers/sig_handler.rb:82:in `parse_node'
	/Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10666/lib/types/private/methods/call_validation.rb:153:in `bind_call'
	/Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10666/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
```

## Workarounds

1. Remove the sig. This doesn't work unless you remove type checking on the file, which is a non-starter for us.
2. Remove yard-sorbet. Also a non-starter.
3. Rename the function to `rate_1` or something similar that doesn't alias the column name. This is awkward and requires fiddling with the code in a way that ruins the convenience and expressiveness of the original alias.

**Comment by lake-effect** [comment]
I'll see if that fixes it, thanks! If not, I'll update the example.

**Comment by lake-effect** [comment]
I tested the doc generation disabling one plugin (and removing the gem) at a time with the latest versions of each, but it's only when I disable the `yard-sorbet` plugin that the error goes away.

I did notice that the error also goes away when `validates :rate, presence: true` is missing. I'll update the example to match that.

**Comment by dduugg** [comment]
I’m still unable to reproduce this, are you able to add a failing test?

**Comment by lake-effect** [comment]
Thanks for taking a look! I'm out of the office in the near future and I've passed it on to teammates for a look. If any of them can figure out the divergence between our configuration and your test case, they'll post here.
