### ISSUE TITLE
Rename gem to `yard_sorbet` to match require path, gem naming guidelines

### ISSUE THREAD

**Issue by andrewhamon** [dduugg/yard-sorbet#3]
Currently, the gem is named `yard-sorbet`, but the require path is `yard_sorbet`. [Gem naming guidlines](https://guides.rubygems.org/name-your-gem/) recommend that multiword gem names be named using underscores, not hyphens.

You could perhaps instead rename the file paths to use hyphens, which would have the added bonus of making `yard --plugin sorbet` work correctly (currently it doesn't, because yard adds a hyphenated rather than underscored prefix), but would continue to violate naming best practices.

It's rather unfortunate that the yard plugin prefix encourages improperly named gems :/

**Comment by andrewhamon** [comment]
I speculatively opened a PR that does the opposite of the title of this issue -- it renames files so that the require path matches the gem name (and matches the convention expected by yard). See https://github.com/dduugg/yard-sorbet/pull/2

**Comment by dduugg** [comment]
Hi @andrewhamon, thanks for the PR. I agree the right approach is to standardize on the hyphenated name. Browsing the [search results](https://rubygems.org/search?utf8=%E2%9C%93&query=yard) in RubyGems.org suggests this is the prevailing style.

**Comment by dduugg** [comment]
Resolved in #3
